### ISSUE TITLE
Reserver un livre

### ISSUE THREAD

**Issue by tchamanbe** [Helpha/GTI510#3]
Pas possible de faire une reservation dans GTI510 Book.
Quand on clique sur reservation, aucun lien nous permet de le faire.

**Comment by TechFred** [comment]
Il y a un max de réservation.  Regarde avec le user admin, c'est
paramétrable

**Comment by tchamanbe** [comment]
J'ai créer un compte, mais à partir de ce nouveau compte, aucune possibilité de réservation. doit-on le faire uniquement avec le user admin?

**Comment by tchamanbe** [comment]
Mème avec Login BookETS
    USER : forget.lexandre@gmail.com
    MDP : Qwerty7
je ne parviens pas à tester la reservation

**Comment by TechFred** [comment]
Quel livre veux-tu louer? Existe t'il des exemplaires de disponibles?

Frédéric Marquis

**Comment by tchamanbe** [comment]
Ok J'ai compris. j'ai cru qu'en cliquant sur reservation on aura un lien qui permet d'aller directement voir les livre qu'on peut reserver.

**Comment by TechFred** [comment]
Je dois fermer mon serveur pour une maintenance.  De retour ce soir ou
demain

**Comment by tchamanbe** [comment]
Salut,
 Je ne parviens pas a me connecter à l'application. Le serveur est toujours fermé?
Alexis

**Comment by TechFred** [comment]
My bad. Petit bogue avec vmware et httpd. C'est up

**Comment by tchamanbe** [comment]
Salut ,
 J'ai reçu de couriel après une réservation.

Alexis

**Comment by tchamanbe** [comment]
Je ne reçoit pas de couriel après une réservation.
Alexis
