### ISSUE TITLE
Je peux voir les réservations des autres

### ISSUE THREAD

**Issue by Helpha** [Helpha/GTI510#6]
Je peux aller voir les réservations des autres utilisateurs en changeant le user ID dans l'URL

http://localhost/GTI510/viewAllReservation.php?userId=19

Est-ce qu'on se fout de la sécurité ou ?

**Comment by TechFred** [comment]
Bahhh... Moi je dirais que oui. C'est dans nos critères cette sécurité?

[EDIT]
Je trouve rien sur des exigences de sécurités dans notre projet. Nous pouvons le corriger au besoin.

**Comment by Helpha** [comment]
FUK DAT
